// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUB2vOT4wjJ0K2zsKkKnXZpM4bQzsqyGg',
    appId: '1:906690962886:web:ba10ee49b2a8aab5bd7ec7',
    messagingSenderId: '906690962886',
    projectId: 'firestore-ebeveyn',
    authDomain: 'firestore-ebeveyn.firebaseapp.com',
    storageBucket: 'firestore-ebeveyn.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLub9ZdPbMC3TKxGHkk-LS32KrG76DLsU',
    appId: '1:906690962886:android:99b2b7025c7cbb21bd7ec7',
    messagingSenderId: '906690962886',
    projectId: 'firestore-ebeveyn',
    storageBucket: 'firestore-ebeveyn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEAM_yxmimWdWKe5jvysyh4yRmFJJSaBA',
    appId: '1:906690962886:ios:e4d5eeebed371d0bbd7ec7',
    messagingSenderId: '906690962886',
    projectId: 'firestore-ebeveyn',
    storageBucket: 'firestore-ebeveyn.appspot.com',
    iosBundleId: 'com.example.ebeveynDestek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUB2vOT4wjJ0K2zsKkKnXZpM4bQzsqyGg',
    appId: '1:906690962886:web:569d6b35503ef8dabd7ec7',
    messagingSenderId: '906690962886',
    projectId: 'firestore-ebeveyn',
    authDomain: 'firestore-ebeveyn.firebaseapp.com',
    storageBucket: 'firestore-ebeveyn.appspot.com',
  );
}
